
const DEFINITIONS={
 accounts:{title:'Chart of Accounts',desc:'Manage the university general ledger account structure.',fields:[['account_code','Account Code','text'],['account_name','Account Name','text'],['account_type','Account Type','select:asset|liability|equity|income|expense'],['parent_id','Parent Account ID','number'],['is_active','Active','checkbox']],cols:['id','account_code','account_name','account_type','parent_id','is_active']},
 invoices:{title:'Student Fee Invoices',desc:'Issue, track and reconcile tuition and institutional charges.',fields:[['invoice_no','Invoice No','text'],['student_id','Student ID','number'],['semester_id','Semester ID','number'],['issue_date','Issue Date','date'],['due_date','Due Date','date'],['subtotal','Subtotal','number'],['discount','Discount','number'],['tax','Tax','number'],['total_amount','Total Amount','number'],['status','Status','select:draft|issued|partially_paid|paid|overdue|cancelled'],['notes','Notes','textarea']],cols:['id','invoice_no','student_id','student_name','issue_date','due_date','total_amount','status']},
 payments:{title:'Fee Payments & Receipts',desc:'Record student payments and payment references.',fields:[['receipt_no','Receipt No','text'],['invoice_id','Invoice ID','number'],['amount','Amount','number'],['payment_date','Payment Date','date'],['method','Method','select:cash|bank|card|mobile_banking|online'],['reference_no','Reference No','text'],['notes','Notes','textarea']],cols:['id','receipt_no','invoice_no','invoice_id','amount','payment_date','method','reference_no']},
 expenses:{title:'Expenses',desc:'Track operating expenses, approvals and payment status.',fields:[['expense_no','Expense No','text'],['category','Category','text'],['description','Description','text'],['amount','Amount','number'],['expense_date','Expense Date','date'],['payment_method','Payment Method','select:cash|bank|card|mobile_banking|online'],['vendor','Vendor','text'],['status','Status','select:pending|approved|paid|cancelled']],cols:['id','expense_no','category','description','amount','expense_date','payment_method','vendor','status']},
 admissions:{title:'Admissions',desc:'Manage applications from submission through enrollment.',fields:[['application_no','Application No','text'],['applicant_name','Applicant Name','text'],['email','Email','email'],['phone','Phone','text'],['program_id','Program ID','number'],['session_name','Session','text'],['application_date','Application Date','date'],['status','Status','select:submitted|under_review|accepted|rejected|waitlisted|enrolled'],['notes','Notes','textarea']],cols:['id','application_no','applicant_name','email','phone','session_name','application_date','status']},
books:{title:'Library Catalogue',desc:'Manage books, copies and library catalogue metadata.',fields:[['isbn','ISBN','text'],['title','Title','text'],['author','Author','text'],['category','Category','text'],['publisher','Publisher','text'],['publication_year','Publication Year','number'],['copies_total','Total Copies','number'],['copies_available','Available Copies','number'],['location','Shelf / Location','text']],cols:['id','isbn','title','author','category','copies_total','copies_available','location']},
loans:{title:'Library Loans',desc:'Issue, return and monitor library resources.',fields:[['book_id','Book ID','number'],['student_id','Student ID','number'],['issue_date','Issue Date','date'],['due_date','Due Date','date'],['return_date','Return Date','date'],['status','Status','select:issued|returned|overdue|lost'],['fine_amount','Fine Amount','number']],cols:['id','book_id','title','student_id','student_name','issue_date','due_date','return_date','status','fine_amount']},
rooms:{title:'Hostel Rooms',desc:'Manage residence inventory and room capacity.',fields:[['hostel_name','Hostel','text'],['room_no','Room No','text'],['floor_no','Floor','number'],['capacity','Capacity','number'],['fee_per_term','Fee / Term','number'],['status','Status','select:available|full|maintenance|inactive']],cols:['id','hostel_name','room_no','floor_no','capacity','fee_per_term','status']},
hostelAllocations:{title:'Hostel Allocations',desc:'Assign students to residential rooms.',fields:[['room_id','Room ID','number'],['student_id','Student ID','number'],['start_date','Start Date','date'],['end_date','End Date','date'],['status','Status','select:active|ended']],cols:['id','room_id','student_id','start_date','end_date','status']},
routes:{title:'Transport Routes',desc:'Manage university buses, routes and pickup points.',fields:[['route_name','Route Name','text'],['vehicle_no','Vehicle No','text'],['driver_name','Driver','text'],['pickup_points','Pickup Points','textarea'],['schedule','Schedule','text'],['status','Status','select:active|inactive']],cols:['id','route_name','vehicle_no','driver_name','pickup_points','schedule','status']},
transportAssignments:{title:'Transport Assignments',desc:'Assign students to transport routes and pickup points.',fields:[['route_id','Route ID','number'],['student_id','Student ID','number'],['pickup_point','Pickup Point','text'],['start_date','Start Date','date'],['end_date','End Date','date'],['status','Status','select:active|ended']],cols:['id','route_id','student_id','pickup_point','start_date','end_date','status']},
staff:{title:'Staff & HR Profiles',desc:'Maintain non-faculty employee records and employment status.',fields:[['user_id','User ID','number'],['department_id','Department ID','number'],['employee_no','Employee No','text'],['job_title','Job Title','text'],['employment_type','Employment Type','select:full_time|part_time|contract|visiting'],['joining_date','Joining Date','date'],['phone','Phone','text'],['status','Status','select:active|inactive|on_leave']],cols:['id','employee_no','name','job_title','department_name','employment_type','joining_date','phone','status']},
announcements:{title:'Announcements & Notices',desc:'Publish official communications to university audiences.',fields:[['title','Title','text'],['body','Message','textarea'],['audience','Audience','select:all|students|faculty|staff|admin'],['publish_at','Publish At','datetime-local'],['expires_at','Expires At','datetime-local'],['status','Status','select:draft|published|archived']],cols:['id','title','audience','publish_at','expires_at','status']},
calendar:{title:'Academic Calendar',desc:'Manage semester dates, exams, registration and university events.',fields:[['title','Title','text'],['event_type','Event Type','select:semester|holiday|exam|registration|event|deadline'],['start_date','Start Date','date'],['end_date','End Date','date'],['description','Description','textarea']],cols:['id','title','event_type','start_date','end_date','description']}
};
const moduleKey=new URLSearchParams(location.search).get('module')||'accounts'; const def=DEFINITIONS[moduleKey];
if(!def){document.body.innerHTML='<p>Unknown module.</p>';}else{
renderShell({active:moduleKey,title:def.title,subtitle:def.desc});
setTimeout(initModule,0);
}
function initModule(){
 const root=document.getElementById('moduleRoot'); if(!root)return;
 const isAdmin=(JSON.parse(localStorage.getItem('user')||'{}').role==='admin');
 root.innerHTML=`<div class="page-toolbar"><div><strong>${def.title}</strong><div class="topbar-sub">${def.desc}</div></div>${isAdmin?'<button id="newBtn">Add Record</button>':''}</div>
 <div class="error" id="errorMsg"></div><div class="success" id="successMsg"></div>
 <div id="formArea"></div><div class="data-table-wrap"><table><thead><tr>${def.cols.map(c=>`<th>${pretty(c)}</th>`).join('')}${isAdmin?'<th>Actions</th>':''}</tr></thead><tbody id="rows"></tbody></table></div>`;
 if(isAdmin)document.getElementById('newBtn').onclick=()=>showForm();
 load();
}
function pretty(s){return s.replace(/_/g,' ').replace(/\b\w/g,x=>x.toUpperCase());}
async function load(){try{const r=await getUniversityModule(moduleKey);document.getElementById('rows').innerHTML=r.data.map(row=>`<tr>${def.cols.map(c=>`<td>${esc(format(row[c]))}</td>`).join('')}${JSON.parse(localStorage.getItem('user')||'{}').role==='admin'?`<td><button class="btn-small btn-edit" onclick='editRecord(${JSON.stringify(row)})'>Edit</button><button class="btn-small btn-delete" onclick="removeRecord(${row.id})">Delete</button></td>`:''}</tr>`).join('')}catch(e){showErr(e.message)}}
function format(v){if(v===null||v===undefined)return '—';if(typeof v==='boolean')return v?'Yes':'No';return v}
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function formHtml(row={}){return `<form id="recordForm" class="form-grid">${def.fields.map(([key,label,type])=>`<div><label>${label}</label>${type==='textarea'?`<textarea name="${key}" rows="3">${esc(row[key]??'')}</textarea>`:type.startsWith('select:')?`<select name="${key}">${type.slice(7).split('|').map(o=>`<option ${String(row[key])===o?'selected':''} value="${o}">${pretty(o)}</option>`).join('')}</select>`:type==='checkbox'?`<input name="${key}" type="checkbox" ${row[key]?'checked':''}>`: `<input name="${key}" type="${type}" value="${esc(row[key]??'')}" ${key==='invoice_no'||key==='receipt_no'||key==='expense_no'||key==='application_no'||key==='employee_no'&&row.id?'':'required'}>`}</div>`).join('')}<div style="grid-column:1/-1"><button>Save</button> <button type="button" class="btn-small" id="cancelBtn">Cancel</button></div></form>`}
function showForm(row={}){const area=document.getElementById('formArea');area.innerHTML=formHtml(row);document.getElementById('cancelBtn').onclick=()=>area.innerHTML='';document.getElementById('recordForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),payload={};def.fields.forEach(([k,,t])=>payload[k]=t==='checkbox'?fd.get(k)!==null:(fd.get(k)===''?null:fd.get(k)));try{if(row.id)await updateUniversityRecord(moduleKey,row.id,payload);else await createUniversityRecord(moduleKey,payload);area.innerHTML='';showOk('Record saved successfully.');load();}catch(x){showErr(x.message)}}}
function editRecord(row){showForm(row);window.scrollTo({top:0,behavior:'smooth'})}
async function removeRecord(id){if(!confirm('Delete this record?'))return;try{await deleteUniversityRecord(moduleKey,id);showOk('Record deleted.');load()}catch(e){showErr(e.message)}}
function showErr(m){const e=document.getElementById('errorMsg');if(e){e.textContent=m;e.style.display='block'}}function showOk(m){const e=document.getElementById('successMsg');if(e){e.textContent=m;e.style.display='block';setTimeout(()=>e.style.display='none',3000)}}
